name: build and deploy a release

on:
  release:
    types: [published]

jobs:
  windows-publishing:
    runs-on: windows-latest
    strategy:
      matrix:
        buildTarget: [MingwX64]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository
  linux-publishing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildTarget: [LinuxX64, LinuxArm32Hfp, LinuxMips32, LinuxMipsel32]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository
  mac-publishing:
    runs-on: macOS-latest
    strategy:
      matrix:
        buildTarget: [MacosX64, IosArm32, IosArm64, IosX64, TvosArm64, TvosX64, WatchosArm32, WatchosArm64, WatchosX86]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository
  host-independent-platforms-publishing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildTarget: [Jvm, Js, AndroidArm32, AndroidArm64, Wasm32]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository
  multiplatform-metadata-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publishMetadataPublicationToBintrayRepository publishKotlinMultiplatformPublicationToBintrayRepository