name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  ubuntu-and-platform-independent-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish -PsnapshotNumber=${{ github.run_number }}
  macos-and-windows-targets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: hostOnlyPublish -PsnapshotNumber=${{ github.run_number }}