name: Build and deploy a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'

jobs:
  native-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble
        run: ./gradlew assemble
        shell: bash
      - name: Test
        run: ./gradlew check
        shell: bash
      - name: Upload snapshot to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_APIKEY: ${{ secrets.BINTRAY_APIKEY }}
          BINTRAY_USER_ORG: ${{ secrets.BINTRAY_USER_ORG }}
        run: ./gradlew bintrayUpload -PsnapshotNumber=${{ github.run_number }}
        shell: bash