name: build and publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  build-check-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
  windows-publishing:
    needs: build-check-all
    runs-on: windows-latest
    strategy:
      matrix:
        buildTarget: [MingwX64]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository -PsnapshotNumber=${{ github.run_number }}
  linux-publishing:
    needs: build-check-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildTarget: [LinuxX64, LinuxArm32Hfp, LinuxMips32, LinuxMipsel32]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository -PsnapshotNumber=${{ github.run_number }}
  mac-publishing:
    needs: build-check-all
    runs-on: macOS-latest
    strategy:
      matrix:
        buildTarget: [MacosX64, IosArm32, IosArm64, IosX64, TvosArm64, TvosX64, WatchosArm32, WatchosArm64, WatchosX86]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository -PsnapshotNumber=${{ github.run_number }}
  host-independent-platforms-publishing:
    needs: build-check-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildTarget: [Jvm, Js, AndroidArm32, AndroidArm64, Wasm32]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish${{ matrix.buildTarget }}PublicationToBintrayRepository -PsnapshotNumber=${{ github.run_number }}
  multiplatform-metadata-publishing:
    needs: build-check-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publishMetadataPublicationToBintrayRepository publishKotlinMultiplatformPublicationToBintrayRepository -PsnapshotNumber=${{ github.run_number }}