name: assemble and check

on:
  push:
    branches-ignore:
      - master
      - '[0-9]+.[0-9]+'
      - 'snapshot/[0-9]+.[0-9]+'
  pull_request:
    branches:
      - stable
      - master


jobs:
  build-check-all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
#      - name: Assemble
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: assemble
#      - name: Check
#        uses: eskatos/gradle-command-action@v1
#        with:
#          arguments: check
      - name: Check
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish --dry-run